### ISSUE TITLE
I am getting following error in retrieving query definition status.

### ISSUE THREAD

**Issue by robin-chilliapple** [salesforce-marketingcloud/FuelSDK-Node-SOAP#114]
```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TLSWrap.onread (net.js:563:26)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  errorPropagatedFrom: 'Request Module inside soapRequest' }
```
Please tell me what was the cause of this and how to handle it.

**Comment by vernak2539** [comment]
Sorry, but this is not enough information to help you. Please provide all the information about what you were doing to get this response and I may be able to help out
